/**
 * Client-side conversion event helpers for Meta, Google Ads, and TikTok.
 *
 * Each `track*` function fires the same logical event on whichever
 * platforms are configured. It's safe to call when no platforms are
 * configured — every call gates on the global being present, so an
 * unconfigured platform is just silently skipped.
 *
 * Event-ID dedupe story:
 *   - Every event takes an `eventId` (UUID, generated by the caller).
 *   - The same eventId is passed to the matching server-side fire from
 *     the Stripe webhook. Meta + TikTok dedupe on event_id; Google Ads
 *     dedupes on transaction_id.
 *
 * PII story:
 *   - Email is passed as raw string to the platform JS; the platform's
 *     own client-side code hashes it before sending. (Meta's fbq does
 *     SHA-256 in its client code; same for TikTok ttq.)
 *   - Server-side mirrors hash explicitly before posting to CAPI/Events.
 */

declare global {
  interface Window {
    fbq?: (...args: unknown[]) => void;
    gtag?: (...args: unknown[]) => void;
    ttq?: {
      page?: () => void;
      track?: (
        event: string,
        properties?: Record<string, unknown>,
        options?: { event_id?: string }
      ) => void;
      identify?: (data: Record<string, unknown>) => void;
    };
    dataLayer?: unknown[];
  }
}

/** RFC4122 v4 UUID generator. Used to mint event IDs that are passed
 *  through Stripe metadata to the webhook for dedupe. */
export function newEventId(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  // Fallback for older browsers — still good enough as a unique tag.
  return "ev-" + Math.random().toString(36).slice(2) + "-" + Date.now().toString(36);
}

interface CommonEventInput {
  /** UUID minted by the caller; passed to webhook for dedupe. */
  eventId: string;
  /** Raw email string. Platform JS handles hashing. */
  email?: string | null;
  /** Numeric value (USD). Defaults to product price for Purchase. */
  value?: number;
  currency?: string;
}

/**
 * User clicked a checkout CTA. Fires before /api/checkout. Mirrors as:
 *   - Meta: InitiateCheckout
 *   - Google: begin_checkout
 *   - TikTok: InitiateCheckout
 */
export function trackInitiateCheckout(input: CommonEventInput): void {
  if (typeof window === "undefined") return;
  const { eventId, email, value = 49, currency = "USD" } = input;

  // Meta
  if (typeof window.fbq === "function") {
    window.fbq(
      "track",
      "InitiateCheckout",
      { value, currency },
      { eventID: eventId }
    );
  }

  // Google Ads / GA4
  if (typeof window.gtag === "function") {
    window.gtag("event", "begin_checkout", {
      transaction_id: eventId,
      value,
      currency,
      ...(email ? { user_data: { email_address: email } } : {}),
    });
  }

  // TikTok
  if (window.ttq && typeof window.ttq.track === "function") {
    if (email && typeof window.ttq.identify === "function") {
      window.ttq.identify({ email });
    }
    window.ttq.track(
      "InitiateCheckout",
      { value, currency, content_id: "compound-os" },
      { event_id: eventId }
    );
  }
}

/**
 * User reached /success and /api/verify confirmed paid. Fires once.
 *   - Meta: Purchase
 *   - Google: purchase (with conversion label if configured)
 *   - TikTok: CompletePayment
 *
 * Server-side mirrors fire from the Stripe webhook for iOS / ATT /
 * ad-blocker coverage. Both ends use the same eventId for dedupe.
 */
export function trackPurchase(input: CommonEventInput): void {
  if (typeof window === "undefined") return;
  const { eventId, email, value = 49, currency = "USD" } = input;

  // Meta
  if (typeof window.fbq === "function") {
    window.fbq(
      "track",
      "Purchase",
      { value, currency },
      { eventID: eventId }
    );
  }

  // Google Ads — conversion event with optional send_to label
  if (typeof window.gtag === "function") {
    const purchaseLabel = process.env.NEXT_PUBLIC_GOOGLE_PURCHASE_LABEL;
    const adsId = process.env.NEXT_PUBLIC_GOOGLE_ADS_ID;
    window.gtag("event", "purchase", {
      transaction_id: eventId,
      value,
      currency,
      ...(adsId && purchaseLabel
        ? { send_to: `${adsId}/${purchaseLabel}` }
        : {}),
    });
  }

  // TikTok
  if (window.ttq && typeof window.ttq.track === "function") {
    if (email && typeof window.ttq.identify === "function") {
      window.ttq.identify({ email });
    }
    window.ttq.track(
      "CompletePayment",
      { value, currency, content_id: "compound-os" },
      { event_id: eventId }
    );
  }
}
